'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditPerson
    
    '''<summary>
    '''NombreLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NombreLbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NombreTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NombreTxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FechaNLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaNLbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FechaFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DayDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''MonthDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MonthDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''YearDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YearDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EdadLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdadLbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''EdadTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdadTxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SexoLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SexoLbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SexDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SexDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPerson As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BackToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackToList As Global.System.Web.UI.WebControls.Button
End Class
